**Nettoyer la mémoire**

In [237]:
### -*-coding:Latin-1 -*
def clearall():
    all = [var for var in globals() if var[0] != "_"]
    for var in all:
        del globals()[var]
        
clearall()

**Librairies**

In [238]:
###Library
import numpy as np
import matplotlib.pyplot as plt
from math import *
import scipy
import scipy.stats
import time 

plt.close("all")

**Paramètres physiques**

In [239]:
######################
hbar=1.0546e-34
c=2.997e8
q=1.60217653e-19 
temp=300
kappa=1.3806622e-23
Nq=3

In [240]:
#####################
UT=kappa*temp/q
beta_m=1/(UT*q) 

**Levels quantum**

In [241]:
#####################
Omega_gap=1.18e15
Omegap=Omega_gap*np.array([-1.0,0.0,3.0])

Ep=hbar*np.diag(Omegap)
Energ=-np.diag([Omegap[0]-Omegap[1],Omegap[0]-Omegap[2],Omegap[1]-Omegap[2]])

**Pauli relaxation**

In [242]:
##############
Gam=-1.e10
Dg=-np.diag([Gam]*3)


#####################
W21=W31=2.e11
W32=1.e11

#######################
####
WW=np.array([W21,W31,W32])
a=np.exp(beta_m*Omegap*hbar)
#######################
####
W=np.zeros((Nq,Nq))
for j in range(1,Nq):
    for k in range(0,j):
        W[k,j]=WW[j-1+k]
        W[j,k]=W[k,j]*a[k]/a[j]
for j in range(Nq):
    W[j,j]=-sum(W[:,j])


**Electromagnetic field**

In [243]:
E0=4.2186e9
####
#####################
M=np.array([9.1e-29,9.1e-29,9.1e-29])
Minf=max(abs(M))

#####################
Energ_Rabi=E0*Minf

**Coulomb parameters**

In [244]:
R=1.e-21
R0=-np.diag([0,2*R,2*R])/hbar

**Numerical paramaeters**

In [245]:
Nt=100000
dt=1/Nt

#####################
Omeg_Rabi=E0*Minf/hbar

**Initial density**

In [246]:
Uinit=np.array([[1,0,0]+[0]*6]).T
Uinit

array([[1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

**Matrix**

In [247]:
def AL(sol):
    resu=np.zeros((9,9))
    ####Add free energies + Coulomb linear
    resu[3:6,6:]=-(Energ+R0)/Omeg_Rabi
    resu[6:,3:6]=(Energ+R0)/Omeg_Rabi
    ####Add relaxation in coherences
    resu[3:6,3:6]=Dg/Omeg_Rabi
    resu[6:,6:]=Dg/Omeg_Rabi
    ####Add relaxation in populations
    resu[:3,:3]=W/Omeg_Rabi

    return resu@sol

In [248]:
AL(Uinit)

array([[-4.91886063e-18],
       [ 4.91886063e-18],
       [ 3.52966918e-57],
       [ 0.00000000e+00],
       [ 0.00000000e+00],
       [ 0.00000000e+00],
       [ 0.00000000e+00],
       [ 0.00000000e+00],
       [ 0.00000000e+00]])

**Functions**

In [249]:
def sol_RK4(dtime,Ntime):
    sol=Uinit
    for t in range(1,Ntime):
        ####
        R1=sol+dtime*AL(sol)/2
        R2=sol+dtime*AL(R1)/2
        R3=sol+dtime*AL(R2)
        #####
        sol=sol+dtime*(AL(sol)+2*AL(R1)+2*AL(R2)+AL(R3))/6
    

    print(sol)
    

In [250]:
sol_RK4(1000*dt,10*Nt)

[[1.00000000e+00]
 [3.78448660e-14]
 [2.71566664e-53]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]


In [251]:
0.43861382+0.13866843+0.42271774

0.9999999900000001